config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'voices#index'
  resources :voices do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voice.rb
class Voice < ApplicationRecord
    validates :content, presence: true, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
    before_action :set_voice, only: [:show, :edit, :update, :destroy]
    def index
        @voices = Voice.all
    end
    def new
        @voice = Voice.new
    end
    def create
        @voice = Voice.new(voice_params)
    if params[:back]
        render :new
    else
        if @voice.save
            redirect_to voices_path, notice: "発言しました"
        else
            render :new
        end
    end
    end
    def edit
        
    end
    def show
        
    end
    def update
        if @voice.update(voice_params)
            redirect_to voices_path, notice:"発言を修正しました"
        else
            render :edit
        end
    end
    def destroy
        @voice.destroy
        redirect_to voices_path, notice:"発言を削除しました"
    end
    def confirm
        @voice = Voice.new(voice_params)
        render :new if @voice.invalid?
    end
    private
    def voice_params
        params.require(:voice).permit(:content)
    end
    def set_voice
        @voice = Voice.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voices_helper.rb
module VoicesHelper
    def choose_new_or_edit
        if action_name == 'new'|| action_name == 'create'
          confirm_blogs_path
        elsif action_name == 'edit'
          blog_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SNSclone1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/voices/_footer.html.erb
<footer>
    ⓒ2020 Naoya Fujio
</footer>

app/views/voices/_form.html.erb
<%= form_with(model: @voice, local: true, url: confirm_voices_path) do |form| %>
  <% if @voice.errors.any? %>
    <div id="error_explanation">
      <h2><%= @voice.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @voice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "発言一覧画面にもどる", voices_path %>

app/views/voices/_header.html.erb
<header>
    <b>VOICE</b>
</header>

app/views/voices/confirm.html.erb
<%= render 'header' %>
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @voice, url: voices_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>発言:<%= @voice.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>
<%= render 'footer' %> 

app/views/voices/edit.html.erb
<%= render 'header' %>
<h2>発言を修正する</h2>
  <%= render 'form' %>
  <%= render 'footer' %> 

app/views/voices/index.html.erb
<%= render 'header' %>
<h1>発言一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>発言</th>
  </tr>
<% @voices.each do |voice| %>
  <tr>
    <td><%= voice.content %></td>
    <td><%= link_to '詳細を確認する', voice_path(voice.id) %></td>
    <td><%= link_to "発言を修正する", edit_voice_path(voice.id) %></td>
    <td><%= link_to '発言を削除する', voice_path(voice.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<%= link_to '新しく発言する', new_voice_path %>
<%= render 'footer' %> 

app/views/voices/new.html.erb
<%= render 'header' %>
<h2>発言する</h2>
<%= render 'form' %> 
<%= render 'footer' %> 

app/views/voices/show.html.erb
<%= render 'header' %>
<h1>発言詳細画面</h1>
<p>内容: <%= @voice.content %></p>
<%= render 'footer' %> 